version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/irisdev/app
  web:
    build:
      context: front
      dockerfile: dockerfile-web
    ports:
      -80:80
    volumes: 
      db: